# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Quique Clari"                                # Your name
  description: "Predoctoral Researcher in Political Science at UAM"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Publications"
        href: publications/index.qmd
      - text: "Ongoing Research"
        href: workingpapers/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
    
    # your social media handles
    right:
      - icon: google
        href: https://scholar.google.com/citations?user=f5PXRCsAAAAJ&hl=es
      - icon: twitter
        href: https://twitter.com/quiqueclari1
      - icon: linkedin
        href: https://www.linkedin.com/in/enrique-clari-galán-012428124/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.enrique.clari@uam.es"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">&#169; 2024 Quique Clari Powered by Quarto Based on Marvin Schmitt </span>
    
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - cosmo 
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true